# Generated by Django 3.1.12 on 2026-04-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Peon', 'Peon'), ('Professor', 'Professor'), ('HOD', 'HOD'), ('Other', 'Other')], default='Teacher', max_length=50),
        ),
    ]
